# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\doc\Programming\Python\Alarm Clock\resource\mainui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(450, 200)
        MainWindow.setMinimumSize(QtCore.QSize(450, 200))
        MainWindow.setMaximumSize(QtCore.QSize(450, 200))
        MainWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("d:\\doc\\Programming\\Python\\Alarm Clock\\resource\\icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("d:\\doc\\Programming\\Python\\Alarm Clock\\resource\\icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.nextAlarmLabel = QtWidgets.QLabel(self.centralwidget)
        self.nextAlarmLabel.setGeometry(QtCore.QRect(270, 0, 181, 31))
        self.nextAlarmLabel.setObjectName("nextAlarmLabel")
        self.clockAlarmToggleButton = QtWidgets.QPushButton(self.centralwidget)
        self.clockAlarmToggleButton.setGeometry(QtCore.QRect(0, 0, 121, 31))
        self.clockAlarmToggleButton.setObjectName("clockAlarmToggleButton")
        self.clockGridWidget = QtWidgets.QWidget(self.centralwidget)
        self.clockGridWidget.setGeometry(QtCore.QRect(0, 40, 451, 151))
        self.clockGridWidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.clockGridWidget.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.clockGridWidget.setObjectName("clockGridWidget")
        self.clockGridLayout = QtWidgets.QGridLayout(self.clockGridWidget)
        self.clockGridLayout.setContentsMargins(0, 0, 0, 0)
        self.clockGridLayout.setObjectName("clockGridLayout")
        self.dateLabel = QtWidgets.QLabel(self.clockGridWidget)
        font = QtGui.QFont()
        font.setPointSize(26)
        self.dateLabel.setFont(font)
        self.dateLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dateLabel.setText("Sunday, September 5, 2021")
        self.dateLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.dateLabel.setObjectName("dateLabel")
        self.clockGridLayout.addWidget(self.dateLabel, 0, 0, 1, 1)
        self.timeLabel = QtWidgets.QLabel(self.clockGridWidget)
        font = QtGui.QFont()
        font.setPointSize(58)
        self.timeLabel.setFont(font)
        self.timeLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.timeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.timeLabel.setObjectName("timeLabel")
        self.clockGridLayout.addWidget(self.timeLabel, 4, 0, 1, 1)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(-1, 43, 451, 161))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.alarmLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.alarmLayout.setContentsMargins(0, 0, 0, 0)
        self.alarmLayout.setObjectName("alarmLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setHorizontalSpacing(6)
        self.formLayout.setVerticalSpacing(0)
        self.formLayout.setObjectName("formLayout")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.verticalLayoutWidget)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.dateTimeEdit)
        self.checkBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox.setObjectName("checkBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.checkBox)
        self.alarmLayout.addLayout(self.formLayout)
        self.listView = QtWidgets.QListView(self.verticalLayoutWidget)
        self.listView.setObjectName("listView")
        self.alarmLayout.addWidget(self.listView)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.alarmLayout.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Alarm Clock"))
        self.nextAlarmLabel.setText(_translate("MainWindow", "TextLabel"))
        self.clockAlarmToggleButton.setText(_translate("MainWindow", "Clock/Alarm"))
        self.timeLabel.setText(_translate("MainWindow", "9:53:03 AM"))
        self.checkBox.setText(_translate("MainWindow", "CheckBox"))
